// <auto-generated />
using System;
using CurrencyConverter.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CurrencyConverter.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CurrencyConverter.Core.Entities.CurrencyConvert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("BaseCurrencyValue");

                    b.Property<decimal>("ConvertedCurrencyValue");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("FromCurrency");

                    b.Property<decimal>("PricePerUnit");

                    b.Property<string>("ToCurrency");

                    b.HasKey("Id");

                    b.ToTable("CurrencyConverts");
                });

            modelBuilder.Entity("CurrencyConverter.Core.Entities.CurrencyTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Currency");

                    b.Property<string>("Table");

                    b.HasKey("Id");

                    b.ToTable("CurrencyTables");
                });

            modelBuilder.Entity("CurrencyConverter.Core.Entities.Rate", b =>
                {
                    b.Property<int>("RateId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CurrencyTableId");

                    b.Property<DateTime>("EffectiveDate");

                    b.Property<decimal>("Mid");

                    b.Property<string>("No");

                    b.HasKey("RateId");

                    b.HasIndex("CurrencyTableId");

                    b.ToTable("Rates");
                });

            modelBuilder.Entity("CurrencyConverter.Core.Entities.Rate", b =>
                {
                    b.HasOne("CurrencyConverter.Core.Entities.CurrencyTable", "CurrencyTable")
                        .WithMany("Rates")
                        .HasForeignKey("CurrencyTableId");
                });
#pragma warning restore 612, 618
        }
    }
}
